name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  release:
    tags:
      - "v[12].[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0]
    name: deno ${{ matrix.deno }} sample
    steps:
      - uses: actions/checkout@master
      - name: setup deno
        uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno test
