name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  release:
    tags:
      - "v[12].[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["v0.35.0", "v0.34.0", "v0.33.0"]
    name: deno ${{ matrix.deno }} sample
    steps:
      - uses: actions/checkout@master
      - name: setup deno
        uses: denolib/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno test
